---
- include: "install_packages.yml"
- include: "install_direnv.yml"

# Can't do it using include task because of some bug with array passing
- name: "Install gems"
  gem: "name={{ item.name }} version={{ item.version }} state=present"
  become: no
  register: result
  until: "not result|failed"
  retries: 2
  environment: ruby_environment
  with_items: "{{ gems }}"

- include: "install_from_url.yml tool={{ item }}"
  with_items: "{{ tools }}"
